export const ActionTypes = {
    USER_BALANCE_START:'USER_BALANCE_START',
    USER_BALANCE_SUCESS:'USER_BALANCE_SUCESS',
    USER_BALANCE_FAIL:'USER_BALANCE_FAIL',
    USER_BALANCE_RELOAD:'USER_BALANCE_RELOAD'
}